//
//  Constants.swift
//  PodLove
//
//  Created by SV-work on 26.06.17.
//  Copyright © 2017 SV-work. All rights reserved.
//

import UIKit

let PRIMARY_GENRE_LIST : [Genre] = [
    .arts,
    .business,
    .comedy,
    .education,
    .gamesHobbies,
    .governmentOrganizations,
    .health,
    .kidsFamily,
    .music,
    .newsPolitics,
    .religionSpirituality,
    .scienceMedicine,
    .societyCulture,
    .sportRecreation,
    .technology,
    .tvFilm]

let STOREFRONTS : [String : String] = [
   "DZ" : "Algeria",
   "AO" : "Angola",
   "AI" : "Anguilla",
   "AG" : "Antigua & Barbuda",
   "AR" : "Argentina",
   "AM" : "Armenia",
   "AU" : "Australia",
   "AT" : "Austria",
   "AZ" : "Azerbaijan",
   "BH" : "Bahrain",
   "BD" : "Bangladesh",
   "BB" : "Barbados",
   "BY" : "Belarus",
   "BE" : "Belgium",
   "BZ" : "Belize",
   "BM" : "Bermuda",
   "BO" : "Bolivia",
   "BW" : "Botswana",
   "BR" : "Brazil",
   "VG" : "British Virgin Islands",
   "BN" : "Brunei",
   "BG" : "Bulgaria",
   "CA" : "Canada",
   "KY" : "Cayman Islands",
   "CL" : "Chile",
   "CN" : "China",
   "CO" : "Colombia",
   "CR" : "Costa Rica",
   "CI" : "Cote D’Ivoire",
   "HR" : "Croatia",
   "CY" : "Cyprus",
   "CZ" : "Czech Republic",
   "DK" : "Denmark",
   "DM" : "Dominica",
   "DO" : "Dominican Rep.",
   "EC" : "Ecuador",
   "EG" : "Egypt",
   "SV" : "El Salvador",
   "EE" : "Estonia",
   "FI" : "Finland",
   "FR" : "France",
   "DE" : "Germany",
   "GH" : "Ghana",
   "GR" : "Greece",
   "GD" : "Grenada",
   "GT" : "Guatemala",
   "GY" : "Guyana",
   "HN" : "Honduras",
   "HK" : "Hong Kong",
   "HU" : "Hungary",
   "IS" : "Iceland",
   "IN" : "India",
   "ID" : "Indonesia",
   "IE" : "Ireland",
   "IL" : "Israel",
   "IT" : "Italy",
   "JM" : "Jamaica",
   "JP" : "Japan",
   "JO" : "Jordan",
   "KZ" : "Kazakstan",
   "KE" : "Kenya",
   "KR" : "Korea, Republic Of",
   "KW" : "Kuwait",
   "LV" : "Latvia",
   "LB" : "Lebanon",
   "LI" : "Liechtenstein",
   "LT" : "Lithuania",
   "LU" : "Luxembourg",
   "MO" : "Macau",
   "MK" : "Macedonia",
   "MG" : "Madagascar",
   "MY" : "Malaysia",
   "MV" : "Maldives",
   "ML" : "Mali",
   "MT" : "Malta",
   "MU" : "Mauritius",
   "MX" : "Mexico",
   "MD" : "Moldova, Republic Of",
   "MS" : "Montserrat",
   "NP" : "Nepal",
   "NL" : "Netherlands",
   "NZ" : "New Zealand",
   "NI" : "Nicaragua",
   "NE" : "Niger",
   "NG" : "Nigeria",
   "NO" : "Norway",
   "OM" : "Oman",
   "PK" : "Pakistan",
   "PA" : "Panama",
   "PY" : "Paraguay",
   "PE" : "Peru",
   "PH" : "Philippines",
   "PL" : "Poland",
   "PT" : "Portugal",
   "QA" : "Qatar",
   "RO" : "Romania",
   "RU" : "Russia",
   "SA" : "Saudi Arabia",
   "SN" : "Senegal",
   "RS" : "Serbia",
   "SG" : "Singapore",
   "SK" : "Slovakia",
   "SI" : "Slovenia",
   "ZA" : "South Africa",
   "ES" : "Spain",
   "LK" : "Sri Lanka",
   "KN" : "St. Kitts & Nevis",
   "LC" : "St. Lucia",
   "VC" : "St. Vincent & The Grenadines",
   "SR" : "Suriname",
   "SE" : "Sweden",
   "CH" : "Switzerland",
   "TW" : "Taiwan",
   "TZ" : "Tanzania",
   "TH" : "Thailand",
   "BS" : "The Bahamas",
   "TT" : "Trinidad & Tobago",
   "TN" : "Tunisia",
   "TR" : "Turkey",
   "TC" : "Turks & Caicos",
   "UG" : "Uganda",
   "GB" : "UK",
   "UA" : "Ukraine",
   "AE" : "United Arab Emirates",
   "UY" : "Uruguay",
   "US" : "USA",
   "UZ" : "Uzbekistan",
   "VE" : "Venezuela",
   "VN" : "Vietnam",
   "YE" : "Yemen",
]

let NETWORKS_LIST : [String] = ["Radiotopia", "Mobile Nations", "Gimlet", "Relay FM", "Panoply", "TWiT",  "5by5", "The Heard", "The Nerdist", "The Incomparable", "Maximum Fun", "ESPN", "BBC World Service", "SModcast", "Revision 3", "Quick & Dirty Tips"]

let NETWORKS_SLOGAN : [String] = [
	"Radiotopia, from PRX, is a curated network of extraordinary, cutting-edge podcasts.",
	"Helping 500 Million consumers a year achieve more through tech.",
	"Gimlet Media is the award-winning narrative podcasting company that aims to help listeners better understand the world and each other",
	"Relay FM is an independent podcast network for people who are creative, curious and maybe even a little obsessive — just like its hosts.",
	"Discover. What do you want to listen to?",
	"The TWiT.tv Netcast Network with Leo Laporte features the #1 ranked technology podcast This Week in Tech, along with over 20 other top-ranked online shows.",
	"5by5 makes podcasts for geeks, designers, developers, gamers, entrepreneurs, and people like you, with shows hosted by people including Dan Benjamin, Merlin Mann, Horace Dediu, and Jeffrey Zeldman.",
	"We are eight indie podcasters who met online as fans of each others' work and recognized in one other kindred spirits; producers with a passion for sound-rich, finely-crafted storytelling.",
	"I am Chris Hardwick. I am on TV a lot and have a blog at nerdist.com. This podcast is basically just me talking about stuff and things with my two nerdy friends Jonah Ray and Matt Mira, and usually someone more famous than all of us.",
	"The Incomparable is a network of podcasts full of smart, funny people who love talking about TV, movies, books, comics, games, sports, and other aspects of popular culture.",
	"Maximum Fun is your home on the internet for things that are awesome.",
	"The Worldwide Leader in Sports",
	"International news, analysis and information from the BBC World Service. In-depth news and sport with audio, video and forums.",
	"SModcast is a weekly podcast featuring filmmaker Kevin Smith and his long-time producing partner Scott Mosier, although guests are occasionally featured.",
	"Revision3 was a San Francisco-based multi-channel Internet television network that creates, produces and distributes Web television shows on niche topics.",
	"Quick and Dirty Tips creates and distributes digital content that offers short, actionable advice from friendly and informed authorities that will help you succeed at work and in life."
]
